### PR TITLE
Randomize stationary position

### PR DESCRIPTION
**Pull request by azgul**
Hey!

It seemed too suspicious to keep reporting the same position when staying stationary (i.e. camping at lures). So I randomized that part. I also cleaned up the project because it wouldn't compile as it was. Now it has a proper project structure like any other Android app.

If you want me to make the randomization configurable, let me know.

### CODE REVIEW

**Comment by SubstituteR** [comment]
Hey thanks!  
I've been a little occupied with life recently, so I haven't been able to work on this project for a while.  I will check this and if all looks right I'll merge it directly in and put up a new build on the beta branch on the Xposed Repo.

**Comment by SubstituteR** [comment]
I noticed that you've created a function for generating a new latlng.  Could you consider using the LatLngFromLatLng function?  You can generate a position using bearing (0-359 degrees) and a distance in km.

**Comment by azgul** [comment]
Aha. I didn't realize that that was what it was doing. I suck at maths too ;) So to retain the same logic with that function I would call it with a very low randomized distance as well as randomized bearing, correct?

**Comment by SubstituteR** [comment]
Yes, pick a bearing at random and a distance at random, min/max for bearing is 0-360 and I'd limit distance to a few meters at most.

**Comment by SubstituteR** [comment]
Issue not fixed or updated.  Closing.

**Pull request closed without merging**
